

namespace :project do
	task :link do 
		project_path = Pathname.new(ARGV.pop)
		project_support_path = project_path + "support"
		project_support_link_path = project_support_path + "dream-framework"
		
		dream_project_path = Pathname.new(__FILE__).dirname.dirname
		
		puts "Project path: #{project_path.realpath}"
		puts "Framework path: #{dream_project_path.realpath}"
		
		unless project_support_path.exist?
			puts "Making support path: #{project_support_path}"
			project_support_path.mkdir
		end
		
		if project_support_link_path.exist?
			puts "Unlinking existing #{project_support_link_path}..."
			project_support_link_path.unlink
		end
		
		relative_path = dream_project_path.relative_path_from(project_support_link_path.dirname)
		project_support_link_path.make_symlink(relative_path)
	end
	
	task :xcconfig do
		project_path = Pathname.new(ARGV.pop)
		project_support_path = project_path + "support"
		project_support_xcconfig_path = project_support_path + "dream-framework.xcconfig"
		
		project_support_xcconfig_path.open("w") do |file|
			file.write(<<-EOF)
// This file is automatically generated.

// The root directory of Dream Project:
DREAM_PROJECT=$(SRCROOT)/support/dream-framework

// Include the basic Dream-Project configuration:
#include "support/dream-project/share/build/dream-framework.xcconfig"
			EOF
		end
	end
end
